In [4]:
import numpy as np

class ff:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        
        self.W_hidden = np.random.rand(hidden_size, input_size)
        self.b_hidden = np.zeros((hidden_size, 1))
        self.W_output = np.random.rand(output_size, hidden_size)
        self.b_output = np.zeros((output_size, 1))
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def forward_propagation(self, x):
        z_hidden = np.dot(self.W_hidden, x) + self.b_hidden
        a_hidden = self.sigmoid(z_hidden)
        
        
        z_output = np.dot(self.W_output, a_hidden) + self.b_output
        a_output = self.sigmoid(z_output)
        
        return a_hidden, a_output


input_size = 3
hidden_size = 4
output_size = 2

nn = ff(input_size, hidden_size, output_size)


x_example = np.array([0.1, 0.2, 0.3])


hidden_activations, output_activations = nn.forward_propagation(x_example)

print(hidden_activations,output_activations)

[[0.53061923 0.58883773 0.54751422 0.58899376]
 [0.53061923 0.58883773 0.54751422 0.58899376]
 [0.53061923 0.58883773 0.54751422 0.58899376]
 [0.53061923 0.58883773 0.54751422 0.58899376]] [[0.80766503 0.83094567 0.81466268 0.83100493]
 [0.68286426 0.70080124 0.68812897 0.70084853]]


In [ ]:
import numpy as np

class FeedForwardNN:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        self.W_hidden = np.random.rand(hidden_size, input_size)
        self.b_hidden = np.zeros((hidden_size, 1))
        self.W_output = np.random.rand(output_size, hidden_size)
        self.b_output = np.zeros((output_size, 1))
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def forward_propagation(self, x):
        z_hidden = np.dot(self.W_hidden, x) + self.b_hidden
        a_hidden = self.sigmoid(z_hidden)
        
        z_output = np.dot(self.W_output, a_hidden) + self.b_output
        a_output = self.sigmoid(z_output)
        
        return a_hidden, a_output
    
    def backpropagation(self, x, y, learning_rate):
        a_hidden, a_output = self.forward_propagation(x)
        y = y.reshape(a_output.shape)
        
        error_output = y - a_output
        delta_output = error_output * self.sigmoid_derivative(a_output)
        
        error_hidden = np.dot(self.W_output.T, delta_output)
        delta_hidden = error_hidden * self.sigmoid_derivative(a_hidden)
        
        self.W_output += learning_rate * np.dot(delta_output, a_hidden.T)
        self.b_output += learning_rate * delta_output
        
        self.W_hidden += learning_rate * np.dot(delta_hidden, x.T)
        self.b_hidden += learning_rate * delta_hidden

input_size = 3
hidden_size = 4
output_size = 2

nn = FeedForwardNN(input_size, hidden_size, output_size)

x_example = np.array([0.1, 0.2, 0.3])
y_example = np.array([0.4, 0.5])

learning_rate = 0.1
nn.backpropagation(x_example, y_example, learning_rate)

In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

input_size = 2
hidden_size = 2
output_size = 1

W_hidden = np.array([[0.5, 0.6], [0.7, 0.8]])
b_hidden = np.array([[0.1], [0.2]])
W_output = np.array([[0.9, 1.0]])
b_output = np.array([[0.3]])

input_combinations = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

for x in input_combinations:
    z_hidden = np.dot(W_hidden, x) + b_hidden
    a_hidden = sigmoid(z_hidden)

    z_output = np.dot(W_output, a_hidden) + b_output
    a_output = sigmoid(z_output)

    print(f"Input: {x}, Output: {a_output[0][0] > 0.5}")

Input: [0 0], Output: True
Input: [0 1], Output: True
Input: [1 0], Output: True
Input: [1 1], Output: True


In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def sgd(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, beta, bhist):
    for i in range(len(x)):
        z_hidden = np.dot(W_hidden, x[i]) + b_hidden
        a_hidden = sigmoid(z_hidden)
        z_output = np.dot(W_output, a_hidden) + b_output
        a_output = sigmoid(z_output)
        
        output_error = a_output - y[i]
        delta_output = 2 * output_error * sigmoid_derivative(a_output)
        
        W_output -= learning_rate * np.outer(delta_output, a_hidden)
        b_output -= learning_rate * delta_output
        
        hidden_error = np.dot(W_output.T, delta_output) * sigmoid_derivative(a_hidden)
        
        W_hidden -= learning_rate * np.outer(hidden_error, x[i])
        b_hidden -= learning_rate * hidden_error
        
        beta = np.vstack((beta, np.concatenate((W_hidden.ravel(), b_hidden))))
    
    bhist.append(beta)
    
    return W_hidden, b_hidden, W_output, b_output


In [3]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def vectorized_sgd(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, beta, bhist):
    num_examples = len(x)
    
    z_hidden = np.dot(W_hidden, x.T) + b_hidden
    a_hidden = sigmoid(z_hidden)
    z_output = np.dot(W_output, a_hidden) + b_output
    a_output = sigmoid(z_output)
    
    output_error = a_output - y.T
    hidden_error = np.dot(W_output.T, output_error) * sigmoid_derivative(a_hidden)
    
    W_output -= learning_rate * np.dot(output_error, a_hidden.T) / num_examples
    b_output -= learning_rate * np.sum(output_error, axis=1, keepdims=True) / num_examples
    
    W_hidden -= learning_rate * np.dot(hidden_error, x) / num_examples
    b_hidden -= learning_rate * np.sum(hidden_error, axis=1, keepdims=True) / num_examples
    
    beta = np.vstack((beta, np.concatenate((W_hidden.ravel(), b_hidden))))
    
    bhist.append(beta)
    
    return W_hidden, b_hidden, W_output, b_output


In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def vectorized_sgd(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, beta):
    num_examples = len(x)
    
    z_hidden = np.dot(W_hidden, x.T) + b_hidden
    a_hidden = sigmoid(z_hidden)
    z_output = np.dot(W_output, a_hidden) + b_output
    a_output = sigmoid(z_output)
    
    output_error = a_output - y.T
    hidden_error = np.dot(W_output.T, output_error) * sigmoid_derivative(a_hidden)
    
    W_output -= learning_rate * np.dot(output_error, a_hidden.T) / num_examples
    b_output -= learning_rate * np.sum(output_error, axis=1, keepdims=True) / num_examples
    
    W_hidden -= learning_rate * np.dot(hidden_error, x) / num_examples
    b_hidden -= learning_rate * np.sum(hidden_error, axis=1, keepdims=True) / num_examples
    
    beta = np.vstack((beta, np.concatenate((W_hidden.ravel(), b_hidden))))
    
    return beta

def calculate_mse(W_hidden, b_hidden, W_output, b_output, x, y):
    z_hidden = np.dot(W_hidden, x.T) + b_hidden
    a_hidden = sigmoid(z_hidden)
    z_output = np.dot(W_output, a_hidden) + b_output
    a_output = sigmoid(z_output)
    
    mse = np.mean((a_output - y.T) ** 2)
    
    return mse

def sgd_with_mse_history(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, num_epochs):
    beta = np.concatenate((W_hidden.ravel(), b_hidden))
    mse_history = []
    
    for epoch in range(num_epochs):
        beta = vectorized_sgd(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, beta)
        mse = calculate_mse(W_hidden, b_hidden, W_output, b_output, x, y)
        mse_history.append(mse)
    
    return np.array(mse_history)

In [1]:
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def vectorized_sgd(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, beta):
    num_examples = len(x)
    
    z_hidden = np.dot(W_hidden, x.T) + b_hidden
    a_hidden = sigmoid(z_hidden)
    z_output = np.dot(W_output, a_hidden) + b_output
    a_output = sigmoid(z_output)
    
    output_error = a_output - y.T
    hidden_error = np.dot(W_output.T, output_error) * sigmoid_derivative(a_hidden)
    
    W_output -= learning_rate * np.dot(output_error, a_hidden.T) / num_examples
    b_output -= learning_rate * np.sum(output_error, axis=1, keepdims=True) / num_examples
    
    W_hidden -= learning_rate * np.dot(hidden_error, x) / num_examples
    b_hidden -= learning_rate * np.sum(hidden_error, axis=1, keepdims=True) / num_examples
    
    beta = np.vstack((beta, np.concatenate((W_hidden.ravel(), b_hidden))))
    
    return beta

def calculate_mse(W_hidden, b_hidden, W_output, b_output, x, y):
    z_hidden = np.dot(W_hidden, x.T) + b_hidden
    a_hidden = sigmoid(z_hidden)
    z_output = np.dot(W_output, a_hidden) + b_output
    a_output = sigmoid(z_output)
    
    mse = np.mean((a_output - y.T) ** 2)
    
    return mse

def sgd_with_mse_history(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, num_epochs):
    beta = np.concatenate((W_hidden.ravel(), b_hidden))
    mse_history = []
    
    for epoch in range(num_epochs):
        beta = vectorized_sgd(W_hidden, b_hidden, W_output, b_output, x, y, learning_rate, beta)
        mse = calculate_mse(W_hidden, b_hidden, W_output, b_output, x, y)
        mse_history.append(mse)
    
    return np.array(mse_history)


plt.figure(figsize=(8, 6))
plt.plot(range(1, len(mse_history) + 1), mse_history, marker='o', linestyle='-')
plt.title('MSE vs. Epoch Number')
plt.xlabel('Epoch Number')
plt.ylabel('Mean Squared Error (MSE)')
plt.grid(True)
plt.show()


NameError: name 'mse_history' is not defined

<Figure size 800x600 with 0 Axes>

NameError: name 'a' is not defined